// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: core/kangarootransaction.proto

package corepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KangarooTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Nonce         uint64                 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Signer        []byte                 `protobuf:"bytes,4,opt,name=signer,proto3" json:"signer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KangarooTransaction) Reset() {
	*x = KangarooTransaction{}
	mi := &file_core_kangarootransaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KangarooTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KangarooTransaction) ProtoMessage() {}

func (x *KangarooTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_core_kangarootransaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KangarooTransaction.ProtoReflect.Descriptor instead.
func (*KangarooTransaction) Descriptor() ([]byte, []int) {
	return file_core_kangarootransaction_proto_rawDescGZIP(), []int{0}
}

func (x *KangarooTransaction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *KangarooTransaction) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *KangarooTransaction) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *KangarooTransaction) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

var File_core_kangarootransaction_proto protoreflect.FileDescriptor

const file_core_kangarootransaction_proto_rawDesc = "" +
	"\n" +
	"\x1ecore/kangarootransaction.proto\x12\x04core\"u\n" +
	"\x13KangarooTransaction\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x16\n" +
	"\x06signer\x18\x04 \x01(\fR\x06signerB\x10Z\x0ecore/pb;corepbb\x06proto3"

var (
	file_core_kangarootransaction_proto_rawDescOnce sync.Once
	file_core_kangarootransaction_proto_rawDescData []byte
)

func file_core_kangarootransaction_proto_rawDescGZIP() []byte {
	file_core_kangarootransaction_proto_rawDescOnce.Do(func() {
		file_core_kangarootransaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_kangarootransaction_proto_rawDesc), len(file_core_kangarootransaction_proto_rawDesc)))
	})
	return file_core_kangarootransaction_proto_rawDescData
}

var file_core_kangarootransaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_kangarootransaction_proto_goTypes = []any{
	(*KangarooTransaction)(nil), // 0: core.KangarooTransaction
}
var file_core_kangarootransaction_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_kangarootransaction_proto_init() }
func file_core_kangarootransaction_proto_init() {
	if File_core_kangarootransaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_kangarootransaction_proto_rawDesc), len(file_core_kangarootransaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_kangarootransaction_proto_goTypes,
		DependencyIndexes: file_core_kangarootransaction_proto_depIdxs,
		MessageInfos:      file_core_kangarootransaction_proto_msgTypes,
	}.Build()
	File_core_kangarootransaction_proto = out.File
	file_core_kangarootransaction_proto_goTypes = nil
	file_core_kangarootransaction_proto_depIdxs = nil
}
