// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: core/block/kangaroo_attestation.proto

package kangarooblockpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KangarooAttestation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        []byte                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	Signer        []byte                 `protobuf:"bytes,2,opt,name=signer,proto3" json:"signer,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KangarooAttestation) Reset() {
	*x = KangarooAttestation{}
	mi := &file_core_block_kangaroo_attestation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KangarooAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KangarooAttestation) ProtoMessage() {}

func (x *KangarooAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_core_block_kangaroo_attestation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KangarooAttestation.ProtoReflect.Descriptor instead.
func (*KangarooAttestation) Descriptor() ([]byte, []int) {
	return file_core_block_kangaroo_attestation_proto_rawDescGZIP(), []int{0}
}

func (x *KangarooAttestation) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *KangarooAttestation) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

func (x *KangarooAttestation) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_core_block_kangaroo_attestation_proto protoreflect.FileDescriptor

const file_core_block_kangaroo_attestation_proto_rawDesc = "" +
	"\n" +
	"%core/block/kangaroo_attestation.proto\x12\x05block\"c\n" +
	"\x13KangarooAttestation\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\fR\x06digest\x12\x16\n" +
	"\x06signer\x18\x02 \x01(\fR\x06signer\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignatureB\x1fZ\x1dcore/block/pb;kangarooblockpbb\x06proto3"

var (
	file_core_block_kangaroo_attestation_proto_rawDescOnce sync.Once
	file_core_block_kangaroo_attestation_proto_rawDescData []byte
)

func file_core_block_kangaroo_attestation_proto_rawDescGZIP() []byte {
	file_core_block_kangaroo_attestation_proto_rawDescOnce.Do(func() {
		file_core_block_kangaroo_attestation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_block_kangaroo_attestation_proto_rawDesc), len(file_core_block_kangaroo_attestation_proto_rawDesc)))
	})
	return file_core_block_kangaroo_attestation_proto_rawDescData
}

var file_core_block_kangaroo_attestation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_block_kangaroo_attestation_proto_goTypes = []any{
	(*KangarooAttestation)(nil), // 0: block.KangarooAttestation
}
var file_core_block_kangaroo_attestation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_block_kangaroo_attestation_proto_init() }
func file_core_block_kangaroo_attestation_proto_init() {
	if File_core_block_kangaroo_attestation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_block_kangaroo_attestation_proto_rawDesc), len(file_core_block_kangaroo_attestation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_block_kangaroo_attestation_proto_goTypes,
		DependencyIndexes: file_core_block_kangaroo_attestation_proto_depIdxs,
		MessageInfos:      file_core_block_kangaroo_attestation_proto_msgTypes,
	}.Build()
	File_core_block_kangaroo_attestation_proto = out.File
	file_core_block_kangaroo_attestation_proto_goTypes = nil
	file_core_block_kangaroo_attestation_proto_depIdxs = nil
}
