gen_proto:
	@protoc --proto_path=. --go_out=. core/transaction/kangaroo_transaction.proto
	@protoc --proto_path=. --go_out=. core/block/kangaroo_body.proto
	@protoc --proto_path=. --go_out=. core/block/kangaroo_attestation.proto